#!/bin/bash
NAME=AudioToText
DIR=/home/ubuntu/AudioToText
USER=ubuntu
GROUP=ubuntu
WORKERS=3
VENV=$DIR/.venv/bin/activate
#BIND=unix:$DIR/run/gunicorn.sock
LOG_LEVEL=error

cd $DIR
source $VENV
exec /home/ubuntu/.local/bin/uv run streamlit run app2.py --server.baseUrlPath=/audiototext --server.port 8501